name: 'hellow-world'
inputs:
  who-to-greet:
    description: 'whom to greet'
    required: true
    default: 'whole world'
outputs: 
  time:
    description: 'time we greeted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.who-to-greeet}}
    